HTTP-router server implementation
Six-SM/calculator pull request #8
Opened 2023-09-16 18:27 UTC by frungl

2023-09-16 23:03 UTC, netkex commented on src/main/kotlin/org/ssm/Server.kt
> +package org.ssm
Думаю стоит добавить еще модуль здесь. То есть по идее, должно быть как минимум 3 модуля:
* org.ssm.api 
* org.ssm.server
* org.ssm.client (или app)

Так будет логическое разделение и классы используемые в нескольких частях (`api`) будут переиспользованы.

2023-09-16 23:10 UTC, volivan239 requested changes
По модулю комментариев все хорошо. Еще я за то чтобы вынести `TemporaryStorage` и `CalculationService` в `object`-ы или что-то в этом духе, потому что вызовы а-ля `save(calculation)`, написанные где-то в другом файле, звучат менее однозначно и понятно, чем `TemporaryStorage.save(calculation)`

2023-09-16 23:10 UTC, volivan239 commented on src/main/kotlin/org/ssm/db/TemporaryStorage.kt
> +
Сделай хотя бы `internal`. Хотя здесь, вроде, можно вообще `private`.

2023-09-16 23:10 UTC, volivan239 commented on src/main/kotlin/org/ssm/db/TemporaryStorage.kt
> +fun getHistory() = temporaryStorage.sortedBy { it.timestamp }
Лучше явно указывать возвращаемые типы, по крайней мере, там где они не `Unit`.

2023-09-16 23:10 UTC, volivan239 commented on src/main/kotlin/org/ssm/plugins/Routing.kt
> +        // GET /api/history
этот комментарий, равно как и комментарий про POST, кажется, совсем не помогает и скорее отвлекает, думаю, их стоит убрать

2023-09-17 12:42 UTC, netkex commented
@volivan239 Я сейчас еще вынесу общий модуль API, посмотри пока на текущий gradle скрипт в целом

2023-09-17 15:01 UTC, volivan239 approved these changes
LGTM

2023-09-17 15:02 UTC, merged